#include <QCoreApplication>
#include <QDebug>
#include <QProcess>



// This header is generated by Flex.
#include "lexer.h"

// This header is generated by bison.
#include "parser.h"


extern int yyparse (void);

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    QProcess::execute("clear");
    qDebug() << "Iniciando\n";

    QString str("1+1\n");

    // Insert the string into the input stream.
    YY_BUFFER_STATE bufferState = yy_scan_string(str.toUtf8().constData());

    // Parse the string.
     yyparse();

    // flush the input stream.
    yy_delete_buffer(bufferState);
    return a.exec();
}
